name: Release

on:
    release:
        types: [published]

jobs:
    test:
        uses: ./.github/workflows/test.yml
        with:
            version: ${{ github.ref_name }}

    build:
        needs: test
        uses: ./.github/workflows/build.yml
        with:
            version: ${{ github.ref_name }}

    publish:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Setup Git user
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Update package.json version
              run: |
                  TAG=${{ github.ref_name }}
                  VERSION=${TAG#v}
                  jq --indent 4 --arg v "$VERSION" '.version = $v' package.json > temp.json && mv temp.json package.json

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-${{ github.ref_name }}
                  path: dist/

            - name: Configure npm auth
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Copy README, LICENSE and package.json to dist
              run: |
                  cp package.json dist/package.json
                  cp README.md dist/
                  cp LICENSE dist/

            - name: Publish to NPM
              working-directory: dist
              run: npm publish --access public
