name: Test

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Update package.json version
              run: |
                  echo "Updating package.json to version ${{ inputs.version }}"
                  jq --arg v "${{ inputs.version }}" '.version = $v' package.json > temp.json && mv temp.json package.json

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run tests
              run: bun test
